<a href="https://colab.research.google.com/github/psa2001/computer_vision/blob/main/notebook_for_cv_1(demozaing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)
#drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd drive

/content/drive


In [ ]:
%cd 'My Drive'

/content/drive/My Drive


In [ ]:
!ls -l 

ls: senukova: No such file or directory
total 21
-rw------- 1 root root 4010 Sep 12 09:03  bayer.py
-rw------- 1 root root  686 Sep 12 08:37  build.sh
drwx------ 2 root root 4096 Apr  8 07:36 'Colab Notebooks'
-rw------- 1 root root 1427 Dec 30  2019  common.py
-rwx------ 1 root root 1904 Sep 12 08:37  run.py
lrw------- 1 root root    0 Apr  7 11:40  senukova -> /content/drive/.shortcut-targets-by-id/1v8OowmZARWubJb2gPirqYtGVZkvULt4o/senukova
drwx------ 2 root root 4096 Apr  8 07:35  senukovs_a
drwx------ 2 root root 4096 Sep 12 08:57  tests


In [ ]:
!chmod +x run.py

In [ ]:
!chmod +x build.sh

In [ ]:
!ls -l 

ls: senukova: No such file or directory
total 21
-rw------- 1 root root 4010 Sep 12 09:03  bayer.py
-rwx------ 1 root root  686 Sep 12 08:37  build.sh
drwx------ 2 root root 4096 Apr  8 07:36 'Colab Notebooks'
-rw------- 1 root root 1427 Dec 30  2019  common.py
-rwx------ 1 root root 1904 Sep 12 08:37  run.py
lrw------- 1 root root    0 Apr  7 11:40  senukova -> /content/drive/.shortcut-targets-by-id/1v8OowmZARWubJb2gPirqYtGVZkvULt4o/senukova
drwx------ 2 root root 4096 Apr  8 07:35  senukovs_a
drwx------ 2 root root 4096 Sep 12 08:57  tests


In [ ]:
!./build.sh

In [ ]:
import numpy as np
n_rows = n_cols = 3

In [ ]:
red = np.zeros([n_rows, n_cols])
red_arr = np.zeros([n_cols])
for i in range(1, n_cols, 2):
    red_arr[i] = 1
for i in range(0, n_rows, 2):
    red[i,:] = red_arr

blue = np.zeros([n_rows, n_cols])
blue_arr = np.zeros([n_cols])
for i in range(0, n_cols, 2):
    blue_arr[i] = 1
for i in range(1, n_rows, 2):
    blue[i,:] = blue_arr


green = np.zeros([n_rows, n_cols])
for i in range (n_rows):
    if(i % 2==0):
        green[i,:] = blue_arr
    else:
        green[i,:] = red_arr

In [ ]:
mask = np.dstack((red, green ,blue))

In [ ]:
answ = np.bool_(mask)

In [ ]:
raw_img = np.array([[1, 2,], [3, 4]], dtype='uint8')

In [ ]:
def get_bayer_masks(n_rows, n_cols):
    import numpy as np
    red = np.zeros([n_rows, n_cols])
    red_arr = np.zeros([n_cols])
    for i in range(1, n_cols, 2):
        red_arr[i] = 1
    for i in range(0, n_rows, 2):
        red[i,:] = red_arr
    
    blue = np.zeros([n_rows, n_cols])
    blue_arr = np.zeros([n_cols])
    for i in range(0, n_cols, 2):
        blue_arr[i] = 1
    for i in range(1, n_rows, 2):
        blue[i,:] = blue_arr
        
    green = np.zeros([n_rows, n_cols])
    for i in range (n_rows):
        if(i % 2==0):
            green[i,:] = blue_arr
        else:
            green[i,:] = red_arr
    
    mask = np.bool_(np.dstack((red, green ,blue)))
    return mask

def get_colored_img(raw_img):
    import numpy as np
    mask = get_bayer_masks(raw_img.shape[0], raw_img.shape[1])
    red_val = raw_img * mask[..., 0]
    green_val = raw_img * mask[..., 1]
    blue_val  = raw_img * mask[..., 2]
    answ = (np.dstack((red_val, green_val ,blue_val)))
    return answ

In [ ]:
raw_img = np.array([[202, 150, 137, 121, 195],
                     [ 94, 113, 217,  68, 248],
                     [208, 170, 109,  67,  22],
                     [ 20,  93, 222,  54,  50],
                     [254, 252,  10, 187, 203]], dtype='uint8')
colored_img = get_colored_img(raw_img)

In [ ]:
def midling_red(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.zeros([color_area.shape[0], color_area.shape[1], 3])
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2], axis = (0, 1))
              num_of_el = np.count_nonzero(mask_of_True[i - 1:i + 2, j - 1:j + 2], axis = (0, 1))
              
              not_cur_val = mid // num_of_el #if cut_elem - is unknown
              is_cur = (num_of_el % 2 == 1) #if cut_elem - is known
              
              cur_val = color_area[i, j, :] #if cut_elem - is known
              is_not_cur = (num_of_el % 2 == 0)#if cut_elem - is unknown
              bil_interp[i, j, :] = is_cur * cur_val + not_cur_val * is_not_cur
    return np.uint8(bil_interp)



def bilinear_interpolation(colored_img):
    import numpy as np
    answ = np.zeros((colored_img.shape[0], colored_img.shape[1], 3), 'uint8')
    r = slice(1, -1), slice(1, -1)
    where_color_el = get_bayer_masks(colored_img.shape[0], colored_img.shape[1])
    answ = midling_red(colored_img, where_color_el)
    return answ

In [ ]:
def midling_red(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.zeros([color_area.shape[0] - 2, color_area.shape[1] - 2])
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
            if(mask_of_True[i][j] == False):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2])
              num_of_el = np.count_nonzero(mask_of_True[i - 1:i + 2, j - 1:j + 2])
              bil_interp[i - 1, j - 1] = mid // num_of_el
            else:
              bil_interp[i - 1, j - 1] = color_area[i][j]
    return np.uint8(bil_interp)

def bilinear_interpolation(colored_img):
    import numpy as np
    answ = np.zeros((colored_img.shape[0], colored_img.shape[1], 3), 'uint8')
    r = slice(1, -1), slice(1, -1)
    where_color_el = get_bayer_masks(colored_img.shape[0], colored_img.shape[1])
    answ[r + (0,)] = midling_red(colored_img[:,:,0], where_color_el[:,:,0])
    answ[r + (1,)] = midling_red(colored_img[:,:,1], where_color_el[:,:,1])
    answ[r + (2,)] = midling_red(colored_img[:,:,2], where_color_el[:,:,2])
    return answ


"\ndef midling_red(color_area, mask_of_True):\n    import numpy as np\n    bil_interp = np.zeros([color_area.shape[0] - 2, color_area.shape[1] - 2])\n    for i in range(1, color_area.shape[0] - 1):\n        for j in range(1, color_area.shape[1] - 1):\n            if(mask_of_True[i][j] == False):\n              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2])\n              num_of_el = np.count_nonzero(mask_of_True[i - 1:i + 2, j - 1:j + 2])\n              bil_interp[i - 1, j - 1] = mid // num_of_el\n            else:\n              bil_interp[i - 1, j - 1] = color_area[i][j]\n    return np.uint8(bil_interp)\n\ndef bilinear_interpolation(colored_img):\n    import numpy as np\n    answ = np.zeros((colored_img.shape[0], colored_img.shape[1], 3), 'uint8')\n    r = slice(1, -1), slice(1, -1)\n    where_color_el = get_bayer_masks(colored_img.shape[0], colored_img.shape[1])\n    answ[r + (0,)] = midling_red(colored_img[:,:,0], where_color_el[:,:,0])\n    answ[r + (1,)] = midling_red(colored

In [ ]:
"""
def red_zone(zone):
  row_first = zone.shape[0]
  col_first = zone.shape[1]
  
  for i in range(1,row_first,2):
    for j in range(1,col_first,2):
      if(i + 1 < row_first):
        zone[i][j] = (zone[i-1][j] + zone[i+1][j])/2
  
  for i in range(1, row_first, 2):
    for j in range(2,col_first,2):
      if(j + 1 < col_first):
        zone[i][j] = (zone[i][j - 1] + zone[i][j + 1])/2

  for j in range(2, col_first, 2):
    if(j + 1 < col_first):
      zone[0][j] = (zone[0][j - 1] + zone[0][j + 1])/2
  
  for i in range(2, row_first, 2):
    for j in range(2, col_first, 2):
      zone[i][j] = 2 * zone[i - 1][j] - zone[i - 2][j] 


def green_zone(zone):
  row_first = zone.shape[0]
  col_first = zone.shape[1]
  for i in range(1, row_first, 2):
    for j in range(2, col_first, 2):
      if(j + 1 < col_first and i + 1 < row_first):
       zone[i][j] = (zone[i - 1][j] + zone[i + 1][j] + zone[i][j - 1] + zone[i][j + 1])/4

  for i in range(2, row_first, 2):
    for j in range(1, col_first, 2):
      if(j + 1 < col_first and i + 1 < row_first):
        zone[i][j] = (zone[i - 1][j]+ zone[i + 1][j] + zone[i][j - 1] + zone[i][j + 1])/4


def blue_zone(zone):
  row_first = zone.shape[0]
  col_first = zone.shape[1]

  for i in range(1, row_first, 2):
    for j in range(1, col_first, 2):
      if(j + 1 < col_first):
        zone[i][j] = (zone[i][j - 1] + zone[i][j + 1])/2
    
    for i in range(2, row_first, 2):
      for j in range(1, col_first, 2):
        if(i + 1 < row_first):
          zone[i][j] =  (zone[i - 1][j] + zone[i + 1][j])/2

    for i in range(2, row_first, 2):
      if(i + 1 < row_first):
        zone[i][0] = (zone[i - 1][0] + zone[i + 1][0])/2

    for i in range(2, row_first, 2):
      for j in range(2, col_first, 2):
        zone[i][j] = 2 * zone[i][j - 1]  - zone[i][j - 2]



def midling_red(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.zeros([color_area.shape[0], color_area.shape[1], 3])
    for i in range(3):
      bil_interp[:,:,i] = np.asarray(color_area[:,:,i])
    red_zone(bil_interp[:,:,0])
    green_zone(bil_interp[:,:,1])
    blue_zone(bil_interp[:,:,2])
    return np.uint8(bil_interp)



def bilinear_interpolation(colored_img):
    import numpy as np
    answ = np.zeros((colored_img.shape[0], colored_img.shape[1], 3), 'uint8')
    r = slice(1, -1), slice(1, -1)
    where_color_el = get_bayer_masks(colored_img.shape[0], colored_img.shape[1])
    answ = midling_red(colored_img, where_color_el)
    return answ
"""

In [ ]:
def midling_red(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.zeros((color_area.shape[0]-2,color_area.shape[1]-2), 'uint8')
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
            num_of_el = 4
            if((i + j) % 2 == 0):
              num_of_el = 2
            if(mask_of_True[i][j] == False):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2])
              bil_interp[i -1, j -1 ] = mid // num_of_el
            else:
              bil_interp[i -1, j -1 ] = color_area[i][j]
    return (bil_interp)


def midling_green(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.array((color_area.shape[0]-2,color_area.shape[1]-2))
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
            num_of_el = 4
            if(mask_of_True[i][j] == False):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2])
              bil_interp[i -1, j -1 ] = mid // num_of_el
            else:
              bil_interp[i -1, j -1 ] = color_area[i][j]
    return np.uint8(bil_interp)

  def midling_blue(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.array((color_area.shape[0]-2,color_area.shape[1]-2))
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
            num_of_el = 4
            if((i + j) % 2 == 0):
              num_of_el = 2
            if(mask_of_True[i][j] == False):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2])
              bil_interp[i -1, j -1 ] = mid // num_of_el
            else:
              bil_interp[i -1, j -1 ] = color_area[i][j]
    return np.uint8(bil_interp)



def bilinear_interpolation(colored_img):
    import numpy as np
    answ = np.zeros((colored_img.shape[0], colored_img.shape[1], 3), 'uint8')
    r = slice(1, -1), slice(1, -1)
    where_color_el = get_bayer_masks(colored_img.shape[0], colored_img.shape[1])
    answ[r + (0,)] = midling_red(colored_img[:,:,0], where_color_el[:,:,0])
    answ[r + (1,)] = midling_red(colored_img[:,:,1], where_color_el[:,:,1])
    answ[r + (2,)] = midling_red(colored_img[:,:,2], where_color_el[:,:,2])
    return answ


In [ ]:
def midling_red(color_area, mask_of_True):
    import numpy as np
    bil_interp = np.zeros([color_area.shape[0], color_area.shape[1], 3])
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2], axis = (0, 1))
              num_of_el = np.count_nonzero(mask_of_True[i - 1:i + 2, j - 1:j + 2], axis = (0, 1))
              
              not_cur_val = mid // num_of_el #if cut_elem - is unknown

              bil_interp[i, j, :] = np.uint8(not_cur_val)
    bil_interp = bil_interp * (1 - (mask_of_True)) + mask_of_True * color_area
    return np.uint8(bil_interp)



def bilinear_interpolation(color_area):  
    import numpy as np
    mask_of_True = get_bayer_masks(color_area.shape[0], color_area.shape[1])
    bil_interp = np.zeros([color_area.shape[0], color_area.shape[1], 3])
    for i in range(1, color_area.shape[0] - 1):
        for j in range(1, color_area.shape[1] - 1):
              mid = np.sum(color_area[i - 1:i + 2, j - 1:j + 2], axis = (0, 1))
              num_of_el = np.sum(mask_of_True[i - 1:i + 2, j - 1:j + 2], axis = (0, 1))
              not_cur_val = mid // num_of_el #if cut_elem - is unknown
              bil_interp[i, j, :] =not_cur_val
    color_area += np.int8(bil_interp * (1 - (mask_of_True))) 
    
    return color_area

In [ ]:
from skimage import img_as_ubyte

raw_img = np.array([[202, 150, 137, 121, 195],
                     [ 94, 113, 217,  68, 248],
                     [208, 170, 109,  67,  22],
                     [ 20,  93, 222,  54,  50],
                     [254, 252,  10, 187, 203]], dtype='uint8')
colored_img = get_colored_img(raw_img)
gt_img = np.zeros((5, 5, 3), 'uint8')
r = slice(1, -1), slice(1, -1)
gt_img[r + (0,)] = np.array([[160, 127,  94],
                          [170, 118,  67],
                          [211, 169, 127]])
gt_img[r + (1,)] = np.array([[113, 106,  68],
                          [130, 109,  63],
                          [ 93,  66,  54]])
gt_img[r + (2,)] = np.array([[155, 217, 232],
                          [138, 219, 184],
                          [121, 222, 136]])

img = img_as_ubyte(bilinear_interpolation(colored_img))

In [ ]:
print(img[r])

[[[160 113 155]
  [127 106 217]
  [ 94  68 232]]

 [[170 130 138]
  [118 109 219]
  [ 67  63 184]]

 [[211  93 121]
  [169  66 222]
  [127  54 136]]]


In [ ]:
print(gt_img[r])

[[[160 113 155]
  [127 106 217]
  [ 94  68 232]]

 [[170 130 138]
  [118 109 219]
  [ 67  63 184]]

 [[211  93 121]
  [169  66 222]
  [127  54 136]]]


In [ ]:
a = np.asarray

In [ ]:
G_cen_R_row = np.asarray([[0, 0, 0.5, 0, 0],
                          [0, -1, 0, -1, 0],
                          [-1, 4, 5, 4, -1],
                          [0, -1, 0, -1, 0], 
                          [0, 0, 0.5, 0, 0]])
  
G_cen_R_col = np.asarray([[0, 0, -1, 0, 0],
                          [0, -1, 0, -1, 0],
                          [0.5, 4, 5, 4, 0.5],
                          [0, -1, 0, -1, 0], 
                          [0, 0, -1, 0, 0]])
  
B_cen = np.asarray([[0, 0, -1.5, 0, 0],
                    [0, 2, 0, 2, 0],
                    [-1.5, 0, 6, 0, -1.5],
                    [0, 2, 0, 2, 0], 
                    [0, 0, -1.5, 0, 0]])

In [ ]:
print(np.sum(G_cen_R_row), np.sum(G_cen_R_col), np.sum(B_cen))

8.0 8.0 8.0


In [ ]:
def improved_red_and_blue_zone(zone, only_red, only_green, only_blue, mask):
  import numpy as np
  impr_zone_red = np.zeros([zone.shape[0], zone.shape[1]])
  impr_zone_blue = np.zeros([zone.shape[0], zone.shape[1]])
  impr_zone_green = np.zeros([zone.shape[0], zone.shape[1]])
  G1 = np.asarray([[0, 0, 0.5, 0, 0],
                  [0, -1, 0, -1, 0],
                  [-1, 4, 5, 4, -1],
                  [0, -1, 0, -1, 0], 
                  [0, 0, 0.5, 0, 0]]) 
    
  G2 = np.asarray([[0, 0, -1, 0, 0],
                  [0, -1, 4, -1, 0],
                  [0.5, 0, 5, 0, 0.5],
                  [0, -1, 4, -1, 0], 
                  [0, 0, -1, 0, 0]]) 
    
  CEN = np.asarray([[0, 0, -1.5, 0, 0],
                    [0, 2, 0, 2, 0],
                    [-1.5, 0, 6, 0, -1.5],
                    [0, 2, 0, 2, 0], 
                    [0, 0, -1.5, 0, 0]]) 

  matr = np.array([[0, 0, -1, 0, 0],
                    [0, 0, 2, 0, 0],
                    [-1, 2, 4, 2, -1],
                    [0, 0, 2, 0, 0],
                    [0, 0, -1, 0, 0]])


  for i in range(2, zone.shape[0] - 2):
    for j in range(2, zone.shape[1] - 2):
      cur_matr = zone[i - 2: i + 3, j - 2: j + 3]
      if(mask[i, j, 1]):
        if(mask[i, j + 1, 0]):
          impr_zone_red[i][j] = np.sum(cur_matr * G1) 
          impr_zone_blue[i][j] = np.sum(cur_matr * G2)
        if(mask[i + 1, j , 0]):
          impr_zone_red[i][j] = np.sum(cur_matr * G2) 
          impr_zone_blue[i][j] = np.sum(cur_matr * G1) 
      else:
        impr_zone_green[i][j] = np.sum(cur_matr * matr)
        if(mask[i,j,2]):
          impr_zone_red[i][j] = np.sum(cur_matr * CEN) 
        elif(mask[i, j, 0]):
          impr_zone_blue[i][j] = np.sum(cur_matr * CEN) 

  only_red += np.uint8(np.clip(( (impr_zone_red // 8) ), 0, 255))
  only_blue += np.uint8(np.clip(( (impr_zone_blue // 8) ), 0, 255))
  only_green += np.uint8(np.clip(( (impr_zone_green // 8) ), 0, 255))




def improved_interpolation(raw_img):
  import numpy as np
  colored_img = get_colored_img(raw_img)
  mask = get_bayer_masks(raw_img.shape[0], raw_img.shape[1]) 
  improved_red_and_blue_zone(raw_img, colored_img[:,:,0], colored_img[:,:,1], colored_img[:,:,2],  mask)
  return colored_img

In [ ]:
raw_img = np.array([[8, 5, 3, 7, 1, 3],
                    [5, 2, 6, 8, 8, 1],
                    [9, 9, 8, 1, 6, 4],
                    [9, 4, 2, 3, 6, 8],
                    [5, 4, 3, 2, 8, 7],
                    [7, 3, 3, 6, 9, 3]], dtype='uint8')

gt_img = np.zeros((6, 6, 3), 'uint8')
r = slice(2, -2), slice(2, -2)
gt_img[r + (0,)] = np.array([[6, 1],
                          [1, 0]])
gt_img[r + (1,)] = np.array([[8, 4],
                          [2, 3]])
gt_img[r + (2,)] = np.array([[7, 2],
                          [2, 2]])
img = img_as_ubyte(improved_interpolation(raw_img))

In [ ]:
print(gt_img[r])

[[[6 8 7]
  [1 4 2]]

 [[1 2 2]
  [0 3 2]]]


In [ ]:
print(img[r])

[[[6 8 7]
  [1 4 2]]

 [[1 2 2]
  [0 3 2]]]


In [ ]:
def compute_psnr(img_pred, img_gt):
  import numpy as np
  predicted = np.float64(img_pred)
  perfect = np.float64(img_gt)
  diff = (predicted - perfect) * (predicted - perfect)
  mse = np.sum(diff) /(img_pred.shape[0] * img_pred.shape[1] * img_pred.shape[2])
  if(mse == 0):
    raise ValueError
  psnr = 10 * np.log10(np.amax(perfect) ** 2 / mse)
  return psnr

In [ ]:
from numpy import array
from pytest import approx, raises

img_pred = array([[[146, 222, 187],
                    [254, 123,  38],
                    [ 57, 255, 135]],
                  [[230, 176, 213],
                    [114,  38, 184],
                    [ 47, 212,  52]],
                  [[100, 111, 170],
                    [ 52, 230, 182],
                    [213,  50, 197]]], dtype='uint8')
img_gt = array([[[254,  60,   6],
                  [216,  53,  14],
                  [106, 185, 239]],
                [[121,  34,  29],
                  [ 49, 139, 149],
                  [  6, 159, 221]],
                [[240,  53, 124],
                  [  3, 194, 227],
                  [ 84,  12, 218]]], dtype='uint8')
print(img_gt.shape)

print(compute_psnr(img_pred, img_gt))

(3, 3, 3)
float64
8.266646150069967


In [ ]:
img_pred = array([[[ 87,  78, 248],
                    [ 92, 239, 239],
                    [119, 239,  48]],
                  [[210, 168, 125],
                    [244, 125, 121],
                    [ 12, 196, 166]],
                  [[ 62,   8,  80],
                    [206, 133, 244],
                    [ 36, 181,  19]]], dtype='uint8')
img_gt = array([[[103,  87,  58],
                  [ 14, 236,  41],
                  [222,  19,  65]],
                [[ 13, 167, 106],
                  [ 40,  27,  95],
                  [147, 223,  38]],
                [[234, 129, 110],
                  [ 35, 225,   0],
                  [ 78, 232,  16]]], dtype='uint8')
print(compute_psnr(img_pred, img_gt))

float64
5.600017920324136
